### ISSUE TITLE
Últimas cinco calificaciones

### ISSUE THREAD

**Issue by felipecalvo** [felipecalvo/saludos-gdd#11]
El enunciado tira "Dicha funcionalidad deberá, además, mostrar un historial de las últimas 5 compras o subastas calificadas".

Ambiguo, así que @ivours hiciste unos radiobuttons para elegir cuál de las dos opciones ver, pero la función que yo había hecho devuelve todas independientemente de si era compra o subasta.

Me da igual cambiarlo, pero qué decidimos? Para mí no es claro.

También me parece que les importa muy poco mientras muestres algo coherente.

**Comment by dgcoder** [comment]
Para mi es las ultimas 5, independientemente si es compra o subasta.

**Comment by felipecalvo** [comment]
Sí, mejor sacá los botoncitos que es más fácil así no hay que andar filtrando nada. @ivours
