### ISSUE TITLE
Indices en campos que usamos para buscar registros

### ISSUE THREAD

**Issue by dgcoder** [felipecalvo/saludos-gdd#12]
Agregar indices en los campos que manda la interfaz por parametro para buscar registros.
Ejemplo: getFuncionalidadesRol(@nombreRol) -> meter un indice en la column rol_nombre

**Comment by felipecalvo** [comment]
No sé cómo se hace eso lol. Lo pusiste para acordarte o para que averigüe? jeje

**Comment by dgcoder** [comment]
Para acordarme. Despues lo agrego.

**Comment by dgcoder** [comment]
@felipecalvo 
Ahi agregue un archivo con los indices que vi que servirian. La idea segun lo que dijo zaffaroni el otro dia es que hay que crearlos despues de la migracion. Cuando puedas fijate en que parte del script irian, ya que vos hiciste la migración sabes cuando termina :8ball: 
La idea es que aceleran las consultas por esos campos, pero relantizan inserts y updates en esas tablas.

**Comment by felipecalvo** [comment]
Dale. Cuando lo pase cierro el issue
El 4/6/2016 18:26, Capitan Falcon <notifications@github.com> escribió:@felipecalvo 
Ahi agregue un archivo con los indices que vi que servirian. La idea segun lo que dijo zaffaroni el otro dia es que hay que crearlos despues de la migracion. Cuando puedas fijate en que parte del script irian, ya que vos hiciste la migración sabes cuando termina 🎱 
La idea es que aceleran las consultas por esos campos, pero relantizan inserts y updates en esas tablas.

**Comment by felipecalvo** [comment]
Ya los pasé. Si va a haber algún cambio que sea consistente (?) entre ambos archivos @dgcoder
