### ISSUE TITLE
Cambio de tipos de datos

### ISSUE THREAD

**Issue by dgcoder** [felipecalvo/saludos-gdd#13]
Cambiar tipos de datos de las columnas CLIE_NRO_DOCUMENT Y EMPR_CUIT de numeric a nvarchar para hacer el filtro opcional.

**Comment by felipecalvo** [comment]
Yo lo hago, pero qué hacemos con esto?

>>Todas las columnas creadas para las nuevas tablas deberán respetar los mismos tipos de datos de las columnas existentes en la tabla principal. A su vez el alumno podrá crear nuevas columnas, claves e identificadores para satisfacer sus necesidades. Pero nunca se podrá inventar información, por ejemplo crear un cliente que nunca existió.

**Comment by felipecalvo** [comment]
No podés convertirlas en el momento en que filtrás? @dgcoder

CONVERT(nvarchar(255), CLIE_NRO_DOCUMENTO)

**Comment by dgcoder** [comment]
Uh me olvide de ese requerimiento.
Ok deja veo como lo hago.
