### ISSUE TITLE
Constraint CHECK en USUA_TIPO

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#15]
Estaba intentando crear un usuario 'Administrador' para testear pero no me deja porque esta la siguiente constraint: CONSTRAINT CK_USUA_TIPO CHECK (USUA_TIPO IN ('Empresa', 'Cliente'))
Como puedo hacer para crear un admin? No me acuerdo si lo habiamos hablado, por ahi me olvide jejeje. HELP!!!

Otra cosa: el USUA_TIPO esta definido en la tabla como un nvarchar(255), pero en el der como un bit. Cambio eso en el der?

Grasiavo'

**Comment by felipecalvo** [comment]
El admin hay que crearlo a mano. Voy a agregar el admin que nos piden a la migración, que es username admin, password w23e

Ya cambié el DER. Cuando pushee cierro

**Comment by ivours** [comment]
Dale, genial!

**Comment by felipecalvo** [comment]
listo @ivours
