### ISSUE TITLE
Sacar ABM Rubros del script de creación inicial

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#16]
Como el tp no pide que implementemos el ABM de Rubros, me parece que sería mejor sacar el ABM de Rubros de la creación de las funcionalidades. Porque cuando muestro todo por pantalla saco la info de ahí y tendría que andar poniendo if's para que no me incluya al ABM de Rubros desde la aplicación. Igual si hay que ponerlo sí o sí porque lo piden, avisame y meto los if's, no pasa naranja ;)

**Comment by felipecalvo** [comment]
sí, en realidad la pregunta es para qué lo ponen como un punto del TP si no hay que hacerlo.
