### ISSUE TITLE
Cambio de contraseña

### ISSUE THREAD

**Issue by felipecalvo** [felipecalvo/saludos-gdd#18]
>A un usuario se le puede asignar un único rol según corresponda a su tipo, además, se deberá tener en cuenta que se pueda modificar el password, tanto por el propio usuario como por el usuario administrativo.

estamos considerando esto? habría que crear una funcionalidad cambio de contraseña que esté presente en los tres roles (cliente, admin, empresa).

igual la ventanita sería distinta, porque el admin puede cambiar la de cualquiera, mientras que el usuario sólo la propia.

se me ocurre que el admin vea primero una ventanita donde seleccione el usuario, y una vez seleccionado, para cambiarle la contraseña lleve a otra ventanita que sí sea reutilizable para clientes y empresas (la diferencia sería que el admin elige respecto a qué usuario es esa ventanita y clientes/empresas siempre se le abre con su propio usuario, no va a andar cambiándole la contraseña al resto...)

perdón si esto ya está en algún lado pero no lo veo en la app. @dgcoder @ivours

**Comment by ivours** [comment]
Mala mia, en la transicion login-menu quedo colgado esto. Despues cuando este en casa lo hago 🤘

**Comment by felipecalvo** [comment]
Ok, pero te parece que lo manejemos como una funcionalidad más o no será necesario?

**Comment by ivours** [comment]
Mm me parece que no lo tenemos que modelar como una funcionalidad, porque es independiente del rol. Las funcionalidades estan ligadas a los roles, mientras que el cambio de password propio esta ligado al usuario, y el cambio de password a otros users desde el admin, iria implementado en el ABM de Usuarios (que solo se muestra para el admin). Es decir, te loguees como cliente, empresa, o admin, (y con cualquiera de sus roles) siempre vas a tener un boton de cambiar contraseña que lo agrego fijo al menu. Despues si sos admin tenes acceso al ABM de Usuarios por lo tanto ahi podes acceder al cambio de password de otros usuarios. Te parece bien asi?

**Comment by felipecalvo** [comment]
Así está bien.
Cuando te pinte agregarlo cerrá el issue. No hay apuro

**Comment by ivours** [comment]
listo (hace rato)
