### ISSUE TITLE
Visibilidad en vendedoresConMayorCantidadDeProductosNoVendidos

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#21]
Falta filtrar por visibilidad en vendedoresConMayorCantidadDeProductosNoVendidos (tiene que recibir el nombre de la visibilidad por parametro)

**Comment by felipecalvo** [comment]
Para mí no, porque también pide ordenar por visibilidad. Y si está filtrado qué voy a ordenar, si son todas de la misma visibilidad...

Lo tomé como (otro más) bug del enunciado y no considerar los filtros. Creí que te había dicho.

Lo cambio pero entonces no ordeno por visibilidad sino sólo por fecha. Puedo hacer asi

**Comment by ivours** [comment]
Aah tenes razon, lo habiamos habladoz que gil. No dije nada entonces, perdona, estaba medio bobo a esa hora 😝
