### ISSUE TITLE
Filtros clientes/empresas

### ISSUE THREAD

**Issue by dgcoder** [felipecalvo/saludos-gdd#24]
@ivours 
Cuando puedas proba las funciones de filtros aver si funca lo que hablamos desde la vista.

Filtro clientes:
filtrarClientes(@nombre, @apellido, @nro_documento, @mail)

Filtro Empresas:
filtrarEmpresas(@razon_social, @cuit, @mail)

Es todo string, el filtro puede ser por uno o varios campos en simultaneo. Manda strings vacios cuando no quieras filtrar por ese campo. Y los filtros por nro de documento y por cuit son exactos.

Ya lo probe desde el sql y anda, pero probalo desde la vista cuando puedas. Si anda cerra este issue, sino avisame.

**Comment by ivours** [comment]
Dale joya, termino con unas validaciones, agrego lo del cambio del password y paso a eso

**Comment by felipecalvo** [comment]
Se me ríe el culo que hayas etiquetado a cuentas existentes @nombre @cuit @mail

**Comment by ivours** [comment]
Listo
