### ISSUE TITLE
Tipo clie_depto

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#26]
Seria mucho quilombo cambiar el tipo de clie_depto a char en vez de usar nvarchar(50)?
Por lo que veo todos los deptos tienen solo una letra, creo que nunca vi tampoco en la realidad uno que tenga mas de una letra (corregidme si me equivoco).
Cualquier cosa avisame @felipecalvo y segun que te parezca a vos lo uso como string o char en la aplicacion (me da exactamente lo mismo usar cualquiera de los dos tipos). Igual si cambiar el tipo implica trabajo extra olvidate, lo dejamos como esta, yo solo pregunto porque veo que todos tienen una sola letra.

Salu2

**Comment by felipecalvo** [comment]
No hay problema, pero me lo decís por algo en particular (además de que en todos los casos es una sola letra?) Porque implicaría validar que el usuario ingrese una sola letra (o podrías limitar el nro de caracteres en el textbox, creo que puede). Si estás dispuesto a eso (?) lo cambio

**Comment by ivours** [comment]
Recien me fije y hay un atributo de los textbox que es maxLength asi que puedo usar eso (de paso lo uso tambien para el codigo postal). Nah yo decia nomas porque nunca iba a pasar de 1 la longitud del string, pero la verdad no creo que afecte en nada dejarlo asi como esta, por mi es lo mismo jajaja. Decime vosSsS que te parece

**Comment by felipecalvo** [comment]
Es que pasa lo mismo que había pasado antes con otra cosa, el enunciado exige que no se puedan cambiar los tipos de los campos que ya existían antes de migrar.
Pero podés poner el maxLength en 1 igual, mejor
El 5/6/2016 14:44, Ivo Stéfano Ursino <notifications@github.com> escribió:Recien me fije y hay un atributo de los textbox que es maxLength asi que puedo usar eso (de paso lo uso tambien para el codigo postal). Nah yo decia nomas porque nunca iba a pasar de 1 la longitud del string, pero la verdad no creo que afecte en nada dejarlo asi como esta, por mi es lo mismo jajaja. Decime vosSsS que te parece

**Comment by ivours** [comment]
Ahhh si, tenes razon, no me acordaba que el enunciado exigia los mismos tipos 😌
Dale uso el maxLength entonces!
