### ISSUE TITLE
Funcion que devuelva todos los roles

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#29]
**Dados los siguientes filtros: nombre (no exacto), habilitado (si/no), siendo ambos filtros opcionales (en caso de no utilizarlos, mando NULL) ; Devolver todos los roles que cumplan los filtros.**
-Nombre: getRoles
-Parametros: nombreRol (lo mando como string), habilitado (lo mando como string)

**Comment by felipecalvo** [comment]
En los casos que los filtros no apliquen conviene que a la DB le envíes null, porque si es NULL con un OR lo solucionamos al toque para descartar el filtro si hay que descartarlo. Bueno, yo lo venía haciendo así... te fijaste lo de DBNull.Value que puse en el doc?
 

    El Domingo, 5 de junio, 2016 21:57:06, Ivo Stéfano Ursino <notifications@github.com> escribió:
 

 Dados los siguientes filtros: nombre (no exacto), habilitado (si/no), siendo ambos filtros opcionales (en caso de no utilizarlos, mando la cadena vacía "") ; Devolver todos los roles que cumplan los filtros.
-Nombre: getRoles
-Parametros: nombreRol (lo mando como string), habilitado (lo mando como string)—

**Comment by ivours** [comment]
@felipecalvo Recien vi lo que me decis, gracias! Ahi modifique el issue :)

**Comment by felipecalvo** [comment]
Ahí vi @ivours que @dgcoder te pedía específicamente que le mandes strings vacíos cuando no querías.

**Debería ser lo mismo** pero yo ya implementé algunas cosas considerando lo de null (en particular la parte de facturas... pero ahí se puede filtrar por fechas así que no sé si se puede manejar de otra forma, no tiene sentido que sea un string vacío). Así que si en ambos casos funciona usamos el protocolo animal... el primero que codea qué manda o recibe, decide qué recibe o manda el otro. :bear: :wolf: :tiger2:

**Comment by ivours** [comment]
@felipecalvo jajajaja dale, voy mirando su codigo y me fijo como lo reciben

**Comment by dgcoder** [comment]
@ivours En el habilitado mandame un 1 o un 0, es un bit en la tabla. Mandalo como string si queres.

**Comment by dgcoder** [comment]
@ivours Listo, manda todo como string, null si no lo usas.
