### ISSUE TITLE
Mapear funcionalidades de los roles a mano

### ISSUE THREAD

**Issue by felipecalvo** [felipecalvo/saludos-gdd#3]
Las funcionalidades de Usuario, Cliente y Empresa tienen que estar mapeadas a mano en el script de migración.

Las funcionalidades y a qué roles las asignaría por default serían las siguientes: (A, C y E son administrador, cliente y empresa)
('ABM Roles'),    A
('ABM Usuarios'),    A
('ABM Rubros'),    A
('ABM Visibilidades'),    A
('Vender'),    C    E
('Comprar/Ofertar'),    C
('Historial de cliente'),    C
('Calificar al vendedor'),    C
('Consulta de facturas'),    C    E
('Listado estadístico')    A

DíganmeN qué piensan, si falta o sobra alguna funcionalidad o si cambiarían algún rol @dgcoder @ivours

**Comment by ivours** [comment]
Está OK.

**Comment by felipecalvo** [comment]
Bueno @ivours, si te parece que sos un gil, como digas.

Ya lo hice, estoy esperando que me confirmen [acá](https://groups.google.com/forum/#!topic/gestiondedatos/gkyBNDWMJJs).
