### ISSUE TITLE
Mostrar publicaciones activas incluyendo filtros

### ISSUE THREAD

**Issue by felipecalvo** [felipecalvo/saludos-gdd#30]
Listar publicaciones activas en forma paginada incluyendo los filtros correspondientes, descripción y múltiples rubros.

**Comment by ivours** [comment]
@felipecalvo te pido otra funcion mas para filtrar publicaciones (esta vez para el cambio de estado):
**Dada una descripcion (texto no exacto), creador (exacto) y estado, devolver una tabla de publicaciones SOLAMENTE con las siguientes columnas (si no se te complica mucho, sino decime) -> PUBL_COD, PUBL_DESCRIPCION, USUA_USERNAME, ESTADO (nombre del estado)**
-Parametros: descripcion, creador, estado
-Nombre: filtrarPublicacionesParaCambioDeEstado

**Comment by felipecalvo** [comment]
Debería estar ordenado por visibilidat?

**Comment by ivours** [comment]
Se, igual que en mercadolibre

**Comment by ivours** [comment]
Aca no se si lo puse o no y si en la consigna lo dice o no, pero no se
deberia filtrar por visibilidad (esta funcion era para las compras no?),
porque al comprador le excede saber eso
El 9 jun. 2016 12:42 PM, "Ivo" <ursinoivo@gmail.com> escribió:

Se, igual que en mercadolibre

**Comment by felipecalvo** [comment]
opciones para discutir:

1. concatenar strings desde la app y hacer toda la consulta desde ahí

2. loopear joineando tables para cada filtro

3. hacer 5-10 funciones iguales en donde varíe la cantidad de parámetros
