### ISSUE TITLE
filtrarClientes (arreglar)

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#31]
Cuando le mando null en alguno o todos los parametros, me devuelve una tabla vacia

**Comment by ivours** [comment]
@felipecalvo supongo que idem para filtrarEmpresas

**Comment by felipecalvo** [comment]
Todo lo que está en `Funciones y SPs.sql` lo hizo @dgcoder, incluye filtrarEmpresas y filtrarClientes. Creo que igual ahí se maneja con los strings vacíos según te dijo

**Comment by ivours** [comment]
@felipecalvo aaaaaaah flashee que lo habias hecho vos eso, por eso mandaba null jajajaja, entonces no dije nada, desp de comer pruebo

**Comment by felipecalvo** [comment]
AAAaaa pero qué pelotudos somos, yo todo este tiempo asumí que me hablabas de las facturas, por eso asumía la culpa. No sé leer.

Bueno, el de facturas está filtrado con null, cuando llegues a ese probalo y avisame :stuck_out_tongue_closed_eyes:

**Comment by ivours** [comment]
@felipecalvo jajajajajaj no nos sabemos comunicar (? Dale dale, cuando pruebe eso te digo! Cierro
