### ISSUE TITLE
modificarCliente

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#32]
@dgcoder 

En este SP recibis todos los datos del cliente independientemente si se modificaron o no. Es decir, yo los que modifique te los mando, y los que no modifique te mando tambien (te los mando los mismos valores que ya estaban seteados).

Pero estaba viendo el codigo, y en una linea haces:

IF SALUDOS.existeTipoYNumeroDeDocumento(@documento, @tipo_documento) = 0

Entonces, en el caso de que yo no este modificando el documento (por lo tanto te mando el valor que estaba seteado antes), este chequeo va a fallar porque el documento ya existe en el usuario que quiero modificar. Para mi la solucion a esto es que te fijes si el documento (tipo y num) que te mando yo existe en cualquier usuario que no sea el que estoy intentando modificar.

Igual por ahi me estoy comiendo algo y esto esta bien, cualquier cosa decime

***Idem para modificarEmpresa***

**Comment by dgcoder** [comment]
@ivours Listo ahi lo arregle/ate con alambre en los dos sps, gracias por avisar.

**Comment by felipecalvo** [comment]
:wrench:
