### ISSUE TITLE
Funcion que devuelva usuarios

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#36]
**Dados los siguientes filtros: username(mando String), tipo(mando String), habilitado(mando String con los valores 0/1 -> si preferis que te lo mande con otro tipo avisame, por mi es lo mismo) ; Devolver los usuarios que cumplan con los mismos**
-Parametros: username, tipo, habilitado
-Nombre: getUsuarios
**En caso de no usar filtro/s, mando string vacio ("")**

**Comment by dgcoder** [comment]
@ivours Listo, pero mandame null en los que no usas.

**Comment by ivours** [comment]
@dgcoder probate desde la base lo que te decia hoy, pasaba todo en null y no me devolvia nada. Cualquier cosa decime

**Comment by ivours** [comment]
Que raro, en un rato vuelvo a probar 😵

**Comment by ivours** [comment]
listo, todo ok
