### ISSUE TITLE
agregarFuncionalidadARol

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#37]
@dgcoder aca podrias recibir como parametros el nombreRol y nombreFuncionalidad? Porque andar manejando id's desde la aplicacion es una paja, porque igualmente tendrias que hacer otras funciones extras que serian getIdRol(nombreRol) y getIdFuncionalidad(nombreFuncionalidad) y se agrega complejidad al pedo. Si lo manejamos con strings directamente hacemos todo de una en un solo SP

**Idem quitarFuncionalidadDeRol**

**Comment by dgcoder** [comment]
@ivours Ok, ahi lo cambie. Pense q iba a ser simple manejar los ids desde C#, pero si es tan paja ya fue, lo cambio yo que es mas facil.
Lo cambie tambien en el quitar.

**Comment by ivours** [comment]
Buenisimo, gracias!
