### ISSUE TITLE
SP altaVisibilidad

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#38]
**SP para alta de las visibilidades**
-Parametros: nombreVisibilidad, costoPorPublicar, costoPorVender, costoPorEnvio
-Nombre: altaVisibilidad

**Comment by dgcoder** [comment]
@ivours Listo

**Comment by ivours** [comment]
@dgcoder La base me tira esta excepcion:

![sin titulo](https://cloud.githubusercontent.com/assets/11710413/15997235/f95f5da6-3107-11e6-9bf7-c4410e2ce61b.png)

**Comment by felipecalvo** [comment]
ya lo arreglé

**Comment by felipecalvo** [comment]
e hice el alta
