### ISSUE TITLE
Fecha del sistema

### ISSUE THREAD

**Issue by dgcoder** [felipecalvo/saludos-gdd#4]
Definir si la fecha queda del lado de la aplicación o de la base, y definir el formato o tipo de dato.

**Comment by felipecalvo** [comment]
ahí pusheé lo necesario para manejar la fecha desde la bd... el procedure asignarFecha recibe una fecha y la asigna. la función fechaActual() la devuelve.

**Comment by felipecalvo** [comment]
hablando de fechas, medio que es un issue aparte pero qué hago con las fechas futuras al migrar? [topic](https://groups.google.com/forum/#!searchin/gestiondedatos/fecha$20del$20sistema/gestiondedatos/nL7FdA1xuA4/1QWQ5OhLAAAJ)

las borro? creo una tabla de publicaciones inconsistentes? hay miles de publicaciones en las que se compró meses después de que haya finalizado.

**Comment by dgcoder** [comment]
Meses despues de que termina la publicacion?

**Comment by felipecalvo** [comment]
Sí. Son compras inconsistentes, no tienen sentido. Y no sé qué hacerlas
El 30/5/2016 12:47, Capitan Falcon <notifications@github.com> escribió:Meses despues de que termina la publicacion?

**Comment by dgcoder** [comment]
Tienen facturas hechas esas compras futuras? Esa fecha de compra en que tabla va? Transacciones, Publicaciones y Facturas?

**Comment by felipecalvo** [comment]
Estuve mirando mejor. Es en la tabla maestra, pero en principio yo migré todo sin distinguir. No pasa en ninguna subasta. Son compras hechas después de que la publicación finaliza, están calificadas y facturadas. No sé si todas, pero muchas de las que vi sí, así que supongo que sí.

La fecha de compra es después de la finalización de la publicación en 21068!!! casos distintos. Las fechas de las facturas también pero eso es igual para todas las publicaciones de todo el sistema.

La idea de transacción es nuestra, serían las compras y las ofertas de subastas. Pero no sé si borrar todas las transacciones inválidas porque tienen facturas asociadas...

**Comment by dgcoder** [comment]
Estoy mirando los 21068 casos y ninguno tiene facturas hechas. Puede ser o no ser tirar un select pelotudo? Veo que tienen calificaciones y esas pelotudeces, pero facturas o items veo todo null.

**Comment by felipecalvo** [comment]
a mí me pasó lo mismo pero después me avivé... lo que pasa es que las facturas no están en las mismas filas. ponele, por cada compra tenés tres+ filas. una que te dice que compró, otra que te dice qué calificó en esa compra, y n filas con los datos de la factura

datos de publicación | datos de compra y comprador | datos de calificación | datos de factura
OK | OK | NULL | NULL
OK | OK | OK | NULL
OK | NULL | NULL | OK <-- varias como esta porque depende de la cantidad de items de la factura

**Comment by felipecalvo** [comment]
Decidí que vamos a ignorar olímpicamente esas inconsistencias.
