### ISSUE TITLE
Funciones: getComisionPublicacion, getComisionVenta, getComisionEnvio

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#40]
**Dado un nombre de visibilidad, devolver la comision por publicacion**
-Parametros: nombreVisibilidad
-Nombre: getComisionPublicacion

**Dado un nombre de visibilidad, devolver la comision por venta**
-Parametros: nombreVisibilidad
-Nombre: getComisionVenta

**Dado un nombre de visibilidad, devolver la comision por envio**
-Parametros: nombreVisibilidad
-Nombre: getComisionEnvio

**Comment by dgcoder** [comment]
@ivours
