### ISSUE TITLE
calificacionesPendientes

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#43]
@felipecalvo en la tabla que devuelve calificacionesPendientes, podrias agregar la columna vendedor (creacion de la publicacion) si no se te complica? Asi muestro al vendedor que estoy calificando en la ventana de calificar.

Graciela

**Comment by felipecalvo** [comment]
Esta función usa todo el tiempo las transacciones que no van a existir más, así que lo dejo para después.

**Comment by felipecalvo** [comment]
No sé cuándo pero lo hice @ivours. Te asigno si quedó piola cerralo
