### ISSUE TITLE
Funcion getItemsFactura

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#44]
**Dado un codigo de factura, devolver los items de la factura**
-Parametros: codigoFactura
-Nombre: getItemsFactura
-Columnas de la tabla a retornar: item_descripcion, item_importe, item_cantidad

**Comment by dgcoder** [comment]
@ivours  Lito, probalo y cerralo.

**Comment by ivours** [comment]
@dgcoder listo, anda joya, cierro
