### ISSUE TITLE
Cambiar radio buttons en Historial del Cliente

### ISSUE THREAD

**Issue by felipecalvo** [felipecalvo/saludos-gdd#47]
Cambiar los filtros: Compra Inmediata por Compras, Subasta por Ofertas.

Para paginar hay una función que te devuelve la cantidad de páginas, pero eso depende de qué es lo que querés mostrar. Cuando llamás a la función SALUDOS.cantidadDePaginasHistorialDe(**usuario**, **filtro**), filtro puede ser **Compras** u **Ofertas**.

(en realidad hago un if, si es 'Compras' te muestro las compras, ELSE te muestro las Ofertas... pero no seas sorete y mandá 'Ofertas' también)

**Comment by ivours** [comment]
Listo
