### ISSUE TITLE
Poner en 0 los hh:mm:ss de los DateTimes ingresados por DateTimePicker

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#52]

**Comment by ivours** [comment]
Es probable que se pueda hacer algo por el estilo, ahora en un toque lo
chequeo

**Comment by felipecalvo** [comment]
SALUDOS @ivours @dgcoder

**Comment by ivours** [comment]
Vaamo manao! Soy un adeecto @felipecalvo @dgcoder
