### ISSUE TITLE
Formato de password de Usuario

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#6]
El password es alfanumerico o tiene cualquier caracter al igual que el username?

**Comment by felipecalvo** [comment]
es el dni en los clientes (números) y el cuit en las empresas (números y guiones). pero cuando crees un usuario vas a poder elegir la password y va a poder tener letras, así que...

**Comment by dgcoder** [comment]
Si los cuit tienen los guiones entonces tiene q ser cualquier caracter, letras numeros y simbolos.
