### ISSUE TITLE
Modificar empresa no entiende que es una modificación y no un alta

### ISSUE THREAD

**Issue by felipecalvo** [felipecalvo/saludos-gdd#65]
Y te dice que razón social y cuit ya existen

**Comment by dgcoder** [comment]
@felipecalvo  Y claro, no te deja cambiar la razon y el cuit a uno que ya exista. No entiendo que tiene?

**Comment by ivours** [comment]
@dgcoder si vos modificas una empresa, le volves a mandar todos sus datos (incluidos los viejos) ademas de los que estas cambiando. entonces si modificas los datos de una empresa pero no modificas su razon social o cuit, no te deja porque dice que estas poniendo una razon social y cuit que ya existen, pero en realidad son los de la empresa que esas modificando, se entiende?

**Comment by felipecalvo** [comment]
No pasa cuando modificás cuit o razón social sino cuando modificás cualquier campo. Es como si hiciera un insert en vez de un update, entonces quedan dos con el mismo cuit+razónsocial
 

    El Lunes, 13 de junio, 2016 0:27:44, Capitan Falcon <notifications@github.com> escribió:
 

 @felipecalvo Y claro, no te deja cambiar la razon y el cuit a uno que ya exista. No entiendo que tiene?—

**Comment by dgcoder** [comment]
Ah cierto ahi lo fixeo

**Comment by ivours** [comment]
es lo que decia en este issue #32

**Comment by dgcoder** [comment]
Lo arregle en clte y me olvide de la empresa, ya lo shupeo

**Comment by ivours** [comment]
piola
