### ISSUE TITLE
Funciones que devuelvan tipo de usuario y roles

### ISSUE THREAD

**Issue by ivours** [felipecalvo/saludos-gdd#7]
2 funciones:
**-Dado un username, devolver el tipo de usuario**
-Nombre funcion: getTipoUsuario
-Parametros: @username

**-Dado un username, devolver su coleccion de roles (nombre de rol)**
-Nombre funcion: getRolesUsuario
-Parametros: @username

**Comment by dgcoder** [comment]
@ivours 
Fijate si funca y cerralo

**Comment by felipecalvo** [comment]
@dgcoder diegol, el script_drop dejalo sólo para las funciones que están en script_creacion_inicial... si querés, las que ya estén 100% seguro que andan y no se tocan más migralas de los archivos auxiliares y pasalas al script_creacion_inicial, y recién ahí ponelas en el drop. sino me vuelvo loco gg

**Comment by ivours** [comment]
@dgcoder getTipoUsuario anda joya. Pero getRolesUsuario me devuelve el nombre de rol de todos los usuarios (me da 95 filas que es la misma cantidad que haciendo un select * from rolesxusuario). Debe ser alguna boludez, cuando lo veas decime y lo pruebo

**Comment by dgcoder** [comment]
@felipecalvo agregue las que estaban en el script_creacion_inicial solamente eh. las otras no. Las mias las meti en un archivo drop aparte.

**Comment by felipecalvo** [comment]
@dgcoder había un par que no sé de dónde habían salido que las saqué. capaz las puso ivo (?). no pasa nada
